apiVersion: apps/v1
kind: Deployment
metadata:
    name: logstore-tester
spec:
    replicas: 1
    selector:
        matchLabels:
            app: logstore-tester
    template:
        metadata:
            labels:
                app: logstore-tester
        spec:
            containers:
                - name: logstore-tester
                  image: garygao90/logstore-tester:latest
#                  image: registry.cn-hangzhou.aliyuncs.com/insightmon/logstore-tester:v1.0.0

                  args: ["--vus", "10", "--duration", "1h"]
                    # 根据需要添加环境变量
                  env:
                      - name: LOGSTORE_URL
                        value: "http://logstore-write:3100/logstore/api/v1/push"
