apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: logstore-tester
spec:
#    schedule: "0 */4 * * *" # 每 4 小时运行一次
    schedule: "*/1 * * * *" # 每分钟运行一次
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: logstore-tester
                          image: registry.cn-hangzhou.aliyuncs.com/insightmon/logstore-tester:latest
                          args: ["--vus", "10", "--duration", "1h"]
                            # 环境变量
                          env:
                              - name: LOGSTORE_URL
                                value: "http://logstore-write:3100/logstore/api/v1/push"
                    restartPolicy: OnFailure
